services:
  galactf-db:
    image: postgres:17.4-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: galactf
      POSTGRES_PASSWORD: galactf
      POSTGRES_DB: galactf
    ports:
      - "5432:5432"
  galactf-redis:
    image: redis:7.4-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
  ctf-bobby-library:
    container_name: bobby_library
    build:
      context: ./python_chals
      dockerfile: ./bobby_library/bobby_library.dockerfile
    restart: unless-stopped
    ports: # TODO: remove this in prod mode
      - "10000:8080"
  ctf-unsecure-notes:
    container_name: unsecure_notes
    build:
      context: ./python_chals
      dockerfile: ./unsecure_notes/unsecure_notes.dockerfile
    restart: unless-stopped
    ports: # TODO: remove this in prod mode
      - "10001:8080"
  ctf-just-a-moment:
    container_name: just_a_moment
    build:
      context: ./python_chals
      dockerfile: ./just_a_moment/just_a_moment.dockerfile
    restart: unless-stopped
    ports: # TODO: remove this in prod mode
      - "10002:8080"
  ctf-cookie-monster:
    container_name: cookie_monster
    build:
      context: ./python_chals
      dockerfile: ./cookie_monster/cookie_monster.dockerfile
    restart: unless-stopped
    ports: # TODO: remove this in prod mode
      - "10003:8080"
  ctf-cookie-monster-squared:
    container_name: cookie_monster_squared
    build:
      context: ./python_chals
      dockerfile: ./cookie_monster_squared/cookie_monster_squared.dockerfile
    restart: unless-stopped
    ports: # TODO: remove this in prod mode
      - "10004:8080"
  ctf-calculator:
    container_name: calculator
    build:
      context: ./python_chals
      dockerfile: ./calculator/calculator.dockerfile
    restart: unless-stopped
    ports: # TODO: remove this in prod mode
      - "10005:8080"
    deploy:
      resources:
        limits:
          memory: 200M
  ctf-claustrophobia:
    container_name: claustrophobia
    build:
      context: ./python_chals
      dockerfile: ./claustrophobia/claustrophobia.dockerfile
    restart: unless-stopped
    ports: # TODO: remove this in prod mode
      - "10006:8080"
  ctf-milksad:
    container_name: milksad
    build:
      context: ./python_chals
      dockerfile: ./milksad/milksad.dockerfile
    restart: unless-stopped
    ports: # TODO: remove this in prod mode
      - "10007:8080"
