// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v6.30.1
// source: challenge_reveal.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChallengeReveal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Difficulty    int32                  `protobuf:"varint,3,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Categories    []string               `protobuf:"bytes,5,rep,name=categories,proto3" json:"categories,omitempty"`
	Attachments   []*Attachment          `protobuf:"bytes,6,rep,name=attachments,proto3" json:"attachments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChallengeReveal) Reset() {
	*x = ChallengeReveal{}
	mi := &file_challenge_reveal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChallengeReveal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChallengeReveal) ProtoMessage() {}

func (x *ChallengeReveal) ProtoReflect() protoreflect.Message {
	mi := &file_challenge_reveal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChallengeReveal.ProtoReflect.Descriptor instead.
func (*ChallengeReveal) Descriptor() ([]byte, []int) {
	return file_challenge_reveal_proto_rawDescGZIP(), []int{0}
}

func (x *ChallengeReveal) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ChallengeReveal) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ChallengeReveal) GetDifficulty() int32 {
	if x != nil {
		return x.Difficulty
	}
	return 0
}

func (x *ChallengeReveal) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ChallengeReveal) GetCategories() []string {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *ChallengeReveal) GetAttachments() []*Attachment {
	if x != nil {
		return x.Attachments
	}
	return nil
}

var File_challenge_reveal_proto protoreflect.FileDescriptor

var file_challenge_reveal_proto_rawDesc = string([]byte{
	0x0a, 0x16, 0x63, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x5f, 0x72, 0x65, 0x76, 0x65,
	0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x67, 0x61, 0x6c, 0x61, 0x63, 0x74,
	0x66, 0x1a, 0x10, 0x61, 0x74, 0x74, 0x61, 0x63, 0x68, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0xce, 0x01, 0x0a, 0x0f, 0x43, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67,
	0x65, 0x52, 0x65, 0x76, 0x65, 0x61, 0x6c, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x64,
	0x69, 0x66, 0x66, 0x69, 0x63, 0x75, 0x6c, 0x74, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0a, 0x64, 0x69, 0x66, 0x66, 0x69, 0x63, 0x75, 0x6c, 0x74, 0x79, 0x12, 0x20, 0x0a, 0x0b, 0x64,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1e, 0x0a,
	0x0a, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x0a, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x12, 0x35, 0x0a,
	0x0b, 0x61, 0x74, 0x74, 0x61, 0x63, 0x68, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x06, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x13, 0x2e, 0x67, 0x61, 0x6c, 0x61, 0x63, 0x74, 0x66, 0x2e, 0x41, 0x74, 0x74,
	0x61, 0x63, 0x68, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x0b, 0x61, 0x74, 0x74, 0x61, 0x63, 0x68, 0x6d,
	0x65, 0x6e, 0x74, 0x73, 0x42, 0x12, 0x5a, 0x10, 0x67, 0x61, 0x6c, 0x61, 0x63, 0x74, 0x66, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_challenge_reveal_proto_rawDescOnce sync.Once
	file_challenge_reveal_proto_rawDescData []byte
)

func file_challenge_reveal_proto_rawDescGZIP() []byte {
	file_challenge_reveal_proto_rawDescOnce.Do(func() {
		file_challenge_reveal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_challenge_reveal_proto_rawDesc), len(file_challenge_reveal_proto_rawDesc)))
	})
	return file_challenge_reveal_proto_rawDescData
}

var file_challenge_reveal_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_challenge_reveal_proto_goTypes = []any{
	(*ChallengeReveal)(nil), // 0: galactf.ChallengeReveal
	(*Attachment)(nil),      // 1: galactf.Attachment
}
var file_challenge_reveal_proto_depIdxs = []int32{
	1, // 0: galactf.ChallengeReveal.attachments:type_name -> galactf.Attachment
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_challenge_reveal_proto_init() }
func file_challenge_reveal_proto_init() {
	if File_challenge_reveal_proto != nil {
		return
	}
	file_attachment_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_challenge_reveal_proto_rawDesc), len(file_challenge_reveal_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_challenge_reveal_proto_goTypes,
		DependencyIndexes: file_challenge_reveal_proto_depIdxs,
		MessageInfos:      file_challenge_reveal_proto_msgTypes,
	}.Build()
	File_challenge_reveal_proto = out.File
	file_challenge_reveal_proto_goTypes = nil
	file_challenge_reveal_proto_depIdxs = nil
}
